/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface JournalEntry {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'timestamp' : Time,
}
export type Mood = { 'sad' : null } |
  { 'happy' : null } |
  { 'neutral' : null };
export interface MoodEntry { 'mood' : Mood, 'timestamp' : Time }
export type PlanOption = { 'premierYearly' : null } |
  { 'premierMonthly' : null } |
  { 'basicSixMonth' : null } |
  { 'premierSixMonth' : null } |
  { 'free' : null } |
  { 'basicYearly' : null } |
  { 'basicMonthly' : null };
export interface Testimonial {
  'name' : string,
  'message' : string,
  'timestamp' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'planExpirationTimestamp' : [] | [Time],
  'planStartTimestamp' : [] | [Time],
  'dateOfBirth' : [] | [string],
  'city' : [] | [string],
  'newsletterOptIn' : boolean,
  'name' : string,
  'isActive' : boolean,
  'email' : [] | [string],
  'state' : [] | [string],
  'phone' : [] | [string],
  'selectedPlan' : PlanOption,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addJournalEntry' : ActorMethod<[string, string], bigint>,
  'addMood' : ActorMethod<[Mood], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkAndHandleExpirations' : ActorMethod<[], undefined>,
  'deleteJournalEntry' : ActorMethod<[bigint], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJournalEntries' : ActorMethod<[], Array<JournalEntry>>,
  'getMoodHistory' : ActorMethod<[], Array<MoodEntry>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordPayment' : ActorMethod<[PlanOption], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'selectPlan' : ActorMethod<[PlanOption], undefined>,
  'submitTestimonial' : ActorMethod<[string, string], undefined>,
  'toggleNewsletterOptIn' : ActorMethod<[boolean], undefined>,
  'updateJournalEntry' : ActorMethod<[bigint, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];