/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Mood = IDL.Variant({
  'sad' : IDL.Null,
  'happy' : IDL.Null,
  'neutral' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const PlanOption = IDL.Variant({
  'premierYearly' : IDL.Null,
  'premierMonthly' : IDL.Null,
  'basicSixMonth' : IDL.Null,
  'premierSixMonth' : IDL.Null,
  'free' : IDL.Null,
  'basicYearly' : IDL.Null,
  'basicMonthly' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'planExpirationTimestamp' : IDL.Opt(Time),
  'planStartTimestamp' : IDL.Opt(Time),
  'dateOfBirth' : IDL.Opt(IDL.Text),
  'city' : IDL.Opt(IDL.Text),
  'newsletterOptIn' : IDL.Bool,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Opt(IDL.Text),
  'state' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
  'selectedPlan' : PlanOption,
});
export const JournalEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : Time,
});
export const MoodEntry = IDL.Record({ 'mood' : Mood, 'timestamp' : Time });
export const Testimonial = IDL.Record({
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addJournalEntry' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addMood' : IDL.Func([Mood], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkAndHandleExpirations' : IDL.Func([], [], []),
  'deleteJournalEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getMoodHistory' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordPayment' : IDL.Func([PlanOption], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'selectPlan' : IDL.Func([PlanOption], [], []),
  'submitTestimonial' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'toggleNewsletterOptIn' : IDL.Func([IDL.Bool], [], []),
  'updateJournalEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Mood = IDL.Variant({
    'sad' : IDL.Null,
    'happy' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const PlanOption = IDL.Variant({
    'premierYearly' : IDL.Null,
    'premierMonthly' : IDL.Null,
    'basicSixMonth' : IDL.Null,
    'premierSixMonth' : IDL.Null,
    'free' : IDL.Null,
    'basicYearly' : IDL.Null,
    'basicMonthly' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'planExpirationTimestamp' : IDL.Opt(Time),
    'planStartTimestamp' : IDL.Opt(Time),
    'dateOfBirth' : IDL.Opt(IDL.Text),
    'city' : IDL.Opt(IDL.Text),
    'newsletterOptIn' : IDL.Bool,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Opt(IDL.Text),
    'state' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
    'selectedPlan' : PlanOption,
  });
  const JournalEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : Time,
  });
  const MoodEntry = IDL.Record({ 'mood' : Mood, 'timestamp' : Time });
  const Testimonial = IDL.Record({
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addJournalEntry' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addMood' : IDL.Func([Mood], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkAndHandleExpirations' : IDL.Func([], [], []),
    'deleteJournalEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'getMoodHistory' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordPayment' : IDL.Func([PlanOption], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'selectPlan' : IDL.Func([PlanOption], [], []),
    'submitTestimonial' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'toggleNewsletterOptIn' : IDL.Func([IDL.Bool], [], []),
    'updateJournalEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };