import { MediaItem } from './types';

export const selfHelpVideos: MediaItem[] = [
  {
    title: 'Understanding Trauma and the Brain',
    description: 'Learn how trauma affects the brain and nervous system, and why healing takes time.',
    url: 'https://www.youtube.com/watch?v=4-tcKYx24aA',
    source: 'The School of Life',
    duration: '6:42',
  },
  {
    title: 'The Power of Vulnerability - Brené Brown',
    description: 'Groundbreaking TED talk on embracing vulnerability as a path to connection and healing.',
    url: 'https://www.youtube.com/watch?v=iCvmsMzlF7o',
    source: 'TED',
    duration: '20:19',
  },
  {
    title: 'How to Practice Self-Compassion',
    description: 'Dr. Kristin Neff explains the three elements of self-compassion and how to cultivate them.',
    url: 'https://www.youtube.com/watch?v=11U0h0DPu7k',
    source: 'Greater Good Science Center',
    duration: '8:15',
  },
  {
    title: 'Polyvagal Theory Explained',
    description: 'Understanding your nervous system and how it responds to stress and safety.',
    url: 'https://www.youtube.com/watch?v=ec3AUMDjtKQ',
    source: 'Therapy in a Nutshell',
    duration: '12:30',
  },
  {
    title: 'Healing from Complex PTSD',
    description: 'Dr. Arielle Schwartz discusses recovery strategies for complex trauma.',
    url: 'https://www.youtube.com/watch?v=oyBKWjHJVJk',
    source: 'Dr. Arielle Schwartz',
    duration: '15:45',
  },
  {
    title: 'Setting Healthy Boundaries',
    description: 'Practical guidance on establishing and maintaining boundaries in relationships.',
    url: 'https://www.youtube.com/watch?v=5Cg2GvPT-yI',
    source: 'Psych2Go',
    duration: '7:22',
  },
  {
    title: 'The Science of Emotional Regulation',
    description: 'Understanding emotions and learning practical techniques to regulate them.',
    url: 'https://www.youtube.com/watch?v=WWloIAQpMcQ',
    source: 'Therapy in a Nutshell',
    duration: '10:18',
  },
  {
    title: 'Overcoming Shame and Self-Criticism',
    description: 'Strategies for breaking free from shame and developing self-acceptance.',
    url: 'https://www.youtube.com/watch?v=dVDnx4jkEpY',
    source: 'The Crappy Childhood Fairy',
    duration: '14:52',
  },
];

export const musicVideos: MediaItem[] = [
  {
    title: 'Peaceful Piano - 3 Hours',
    description: 'Gentle piano melodies for relaxation, study, or meditation.',
    url: 'https://www.youtube.com/watch?v=lTRiuFIWV54',
    source: 'Peaceful Piano',
    duration: '3:00:00',
  },
  {
    title: 'Nature Sounds - Forest Rain',
    description: 'Calming rain sounds in a peaceful forest setting for stress relief.',
    url: 'https://www.youtube.com/watch?v=nDq6TstdEi8',
    source: 'Nature Sounds',
    duration: '2:00:00',
  },
  {
    title: 'Healing 528Hz Music',
    description: 'Solfeggio frequency music for deep healing and positive transformation.',
    url: 'https://www.youtube.com/watch?v=EKTZ151yLnk',
    source: 'Meditative Mind',
    duration: '1:00:00',
  },
  {
    title: 'Ocean Waves for Sleep',
    description: 'Gentle ocean waves to help you relax and fall asleep naturally.',
    url: 'https://www.youtube.com/watch?v=V1bFr2SWP1I',
    source: 'Relaxing White Noise',
    duration: '10:00:00',
  },
  {
    title: 'Tibetan Singing Bowls',
    description: 'Healing sounds of Tibetan singing bowls for meditation and chakra balancing.',
    url: 'https://www.youtube.com/watch?v=3eYJXVeQDtM',
    source: 'Meditative Mind',
    duration: '1:30:00',
  },
  {
    title: 'Calm Guitar Music',
    description: 'Soothing acoustic guitar melodies for relaxation and stress relief.',
    url: 'https://www.youtube.com/watch?v=2OEL4P1Rz04',
    source: 'Relaxing Guitar',
    duration: '2:30:00',
  },
  {
    title: 'Binaural Beats for Anxiety Relief',
    description: 'Theta waves designed to reduce anxiety and promote deep relaxation.',
    url: 'https://www.youtube.com/watch?v=WPni755-Krg',
    source: 'Greenred Productions',
    duration: '1:00:00',
  },
  {
    title: 'Zen Garden Meditation Music',
    description: 'Peaceful Asian-inspired music with nature sounds for mindfulness practice.',
    url: 'https://www.youtube.com/watch?v=1ZYbU82GVz4',
    source: 'Yellow Brick Cinema',
    duration: '3:00:00',
  },
];

export const guidedMeditations: MediaItem[] = [
  {
    title: 'Body Scan Meditation for Beginners',
    description: 'Gentle 10-minute body scan to release tension and increase body awareness.',
    url: 'https://www.youtube.com/watch?v=15q-N-_kkrU',
    source: 'The Mindful Movement',
    duration: '10:00',
  },
  {
    title: 'Loving-Kindness Meditation',
    description: 'Cultivate compassion for yourself and others with this guided metta practice.',
    url: 'https://www.youtube.com/watch?v=sz7cpV7ERsM',
    source: 'UCLA Mindful',
    duration: '12:00',
  },
  {
    title: 'Grounding Meditation for Anxiety',
    description: 'Quick grounding technique to calm anxiety and return to the present moment.',
    url: 'https://www.youtube.com/watch?v=ihO02wUzgkc',
    source: 'Great Meditation',
    duration: '8:30',
  },
  {
    title: 'Sleep Meditation - Let Go of Stress',
    description: 'Deeply relaxing guided meditation to help you fall asleep peacefully.',
    url: 'https://www.youtube.com/watch?v=aEqlQvczMJQ',
    source: 'Jason Stephenson',
    duration: '45:00',
  },
  {
    title: 'Healing Inner Child Meditation',
    description: 'Compassionate meditation for connecting with and healing your inner child.',
    url: 'https://www.youtube.com/watch?v=Jl7pDJRbJZs',
    source: 'The Mindful Movement',
    duration: '20:00',
  },
  {
    title: 'Morning Meditation for Positive Energy',
    description: 'Start your day with intention, gratitude, and positive energy.',
    url: 'https://www.youtube.com/watch?v=ZToicYcHIOU',
    source: 'Great Meditation',
    duration: '10:00',
  },
  {
    title: 'Chakra Healing Meditation',
    description: 'Balance and align your seven chakras with this guided visualization.',
    url: 'https://www.youtube.com/watch?v=cH-HT9WCtiQ',
    source: 'Meditative Mind',
    duration: '30:00',
  },
  {
    title: 'Mindfulness Meditation for Beginners',
    description: 'Learn the basics of mindfulness with this gentle introduction.',
    url: 'https://www.youtube.com/watch?v=6p_yaNFSYao',
    source: 'Goodful',
    duration: '5:00',
  },
];

export const educationalSeries: MediaItem[] = [
  {
    title: 'Therapy in a Nutshell - Anxiety Series',
    description: 'Comprehensive video series on understanding and managing anxiety (30+ videos).',
    url: 'https://www.youtube.com/playlist?list=PLiUrrIiqidTWje37Fxv_HFDwJNjY-yc7B',
    source: 'Therapy in a Nutshell',
    duration: 'Series',
  },
  {
    title: 'The Crappy Childhood Fairy - CPTSD Recovery',
    description: 'Practical strategies for healing from childhood trauma and complex PTSD.',
    url: 'https://www.youtube.com/c/CrappyChildhoodFairy',
    source: 'The Crappy Childhood Fairy',
    duration: 'Series',
  },
  {
    title: 'Patrick Teahan - Childhood Trauma Recovery',
    description: 'Licensed therapist shares insights on healing from childhood trauma.',
    url: 'https://www.youtube.com/c/PatrickTeahanLICSW',
    source: 'Patrick Teahan LICSW',
    duration: 'Series',
  },
  {
    title: 'Dr. Tracey Marks - Mental Health Education',
    description: 'Psychiatrist explains mental health conditions and treatment options.',
    url: 'https://www.youtube.com/c/DrTraceyMarks',
    source: 'Dr. Tracey Marks',
    duration: 'Series',
  },
  {
    title: 'Psych2Go - Mental Health Awareness',
    description: 'Animated videos making psychology and mental health accessible to everyone.',
    url: 'https://www.youtube.com/c/Psych2go',
    source: 'Psych2Go',
    duration: 'Series',
  },
  {
    title: 'Kati Morton - Therapy Topics',
    description: 'Licensed therapist discusses various mental health topics and coping strategies.',
    url: 'https://www.youtube.com/c/Katimorton',
    source: 'Kati Morton',
    duration: 'Series',
  },
  {
    title: 'The School of Life - Emotional Intelligence',
    description: 'Philosophical and psychological insights for better understanding yourself and others.',
    url: 'https://www.youtube.com/c/theschooloflifetv',
    source: 'The School of Life',
    duration: 'Series',
  },
  {
    title: 'Irene Lyon - Nervous System Healing',
    description: 'Somatic experiencing and nervous system regulation techniques.',
    url: 'https://www.youtube.com/c/IreneLyon',
    source: 'Irene Lyon',
    duration: 'Series',
  },
];
