/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Testimonial {
    name: string;
    message: string;
    timestamp: bigint;
}
export interface Goal {
    id: bigint;
    title: string;
    isCompleted: boolean;
    goalType: GoalType;
    userId: Principal;
    currentProgress: bigint;
    description: string;
    trophyId?: bigint;
    category: GoalCategory;
    targetValue: bigint;
    completionTimestamp?: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Trophy {
    id: bigint;
    title: string;
    dateEarned?: bigint;
    discountCode?: string;
    userId: Principal;
    description: string;
    imageIdentifier: string;
    discountPercentage?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Event {
    id: bigint;
    startTime: bigint;
    title: string;
    endTime: bigint;
    description: string;
    location: string;
}
export interface CourseFolder {
    files: Array<CourseFile>;
    folderName: string;
}
export interface MoodEntry {
    mood: Mood;
    timestamp: bigint;
}
export interface ProductSuggestion {
    id: bigint;
    suggestion: string;
    author: Principal;
    timestamp: bigint;
}
export interface CourseFile {
    blob: ExternalBlob;
    fileName: string;
}
export interface JournalEntry {
    id: bigint;
    title: string;
    content: string;
    timestamp: bigint;
}
export interface MeetingLink {
    id: bigint;
    url: string;
    title: string;
    timestamp: bigint;
}
export interface PdfFile {
    id: bigint;
    blob: ExternalBlob;
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    couponCode?: string;
    planExpirationTimestamp?: bigint;
    planStartTimestamp?: bigint;
    dateOfBirth?: string;
    city?: string;
    newsletterOptIn: boolean;
    name: string;
    isActive: boolean;
    email?: string;
    state?: string;
    phone?: string;
    selectedPlan: PlanOption;
}
export enum GoalCategory {
    breathingTool = "breathingTool",
    moodLog = "moodLog",
    none = "none",
    therapySession = "therapySession",
    groundingTool = "groundingTool",
    groupClass = "groupClass",
    reframingTool = "reframingTool",
    journaling = "journaling"
}
export enum GoalType {
    streak = "streak",
    milestone = "milestone"
}
export enum Mood {
    sad = "sad",
    happy = "happy",
    neutral = "neutral"
}
export enum PlanOption {
    premierYearly = "premierYearly",
    premierMonthly = "premierMonthly",
    basicSixMonth = "basicSixMonth",
    premierSixMonth = "premierSixMonth",
    free = "free",
    basicYearly = "basicYearly",
    basicMonthly = "basicMonthly"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCourseFolder(token: string, folderName: string, files: Array<CourseFile>): Promise<void>;
    addJournalEntry(title: string, content: string): Promise<bigint>;
    addMeetingLink(token: string, title: string, url: string): Promise<void>;
    addMood(mood: Mood): Promise<void>;
    addOrUpdatePromoCode(_token: string, _code: string, _discountPercentage: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    authenticatePlaybookUser(_username: string, _password: string): Promise<boolean>;
    changePlaybookPassword(_token: string, _newPassword: string): Promise<void>;
    checkAndHandleCallerExpiration(): Promise<void>;
    checkAndHandleSystemExpirations(): Promise<void>;
    createEvent(token: string, title: string, description: string, startTime: bigint, endTime: bigint, location: string): Promise<void>;
    createGoal(title: string, description: string, goalType: GoalType, category: GoalCategory, targetValue: bigint, trophyId: bigint | null): Promise<bigint>;
    createTrophyTemplate(title: string, description: string, imageIdentifier: string, discountPercentage: bigint | null): Promise<bigint>;
    deleteEvent(token: string, id: bigint): Promise<boolean>;
    deleteJournalEntry(id: bigint): Promise<boolean>;
    deleteMeetingLink(token: string, id: bigint): Promise<boolean>;
    editEvent(token: string, id: bigint, title: string, description: string, startTime: bigint, endTime: bigint, location: string): Promise<boolean>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCouponCode(): Promise<string | null>;
    getCourseFolder(token: string, folderName: string): Promise<CourseFolder | null>;
    getEvents(): Promise<Array<Event>>;
    getJournalEntries(): Promise<Array<JournalEntry>>;
    getMeetingLinks(): Promise<Array<MeetingLink>>;
    getMoodHistory(): Promise<Array<MoodEntry>>;
    getTestimonials(): Promise<Array<Testimonial>>;
    getUserGoals(user: Principal): Promise<Array<Goal>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserTrophies(user: Principal): Promise<Array<Trophy>>;
    isCallerAdmin(): Promise<boolean>;
    keepTokenActive(token: string): Promise<void>;
    listCourseFolders(): Promise<Array<CourseFolder>>;
    listPdfFiles(): Promise<Array<PdfFile>>;
    listProductSuggestions(): Promise<Array<ProductSuggestion>>;
    logoutPlaybookUser(token: string): Promise<void>;
    recordGroupClassAttendance(): Promise<void>;
    recordPayment(plan: PlanOption): Promise<void>;
    recordTherapySession(): Promise<void>;
    recordToolUsage(toolCategory: GoalCategory): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCouponCode(code: string): Promise<void>;
    savePdfFile(token: string, name: string, blob: ExternalBlob): Promise<void>;
    selectPlan(plan: PlanOption): Promise<void>;
    submitProductSuggestion(suggestion: string): Promise<void>;
    submitTestimonial(name: string, message: string): Promise<void>;
    toggleNewsletterOptIn(optIn: boolean): Promise<void>;
    updateGoalProgress(goalId: bigint, progress: bigint): Promise<void>;
    updateJournalEntry(id: bigint, title: string, content: string): Promise<boolean>;
    validatePlaybookToken(token: string): Promise<boolean>;
}
import type { CourseFile as _CourseFile, CourseFolder as _CourseFolder, ExternalBlob as _ExternalBlob, Goal as _Goal, GoalCategory as _GoalCategory, GoalType as _GoalType, Mood as _Mood, MoodEntry as _MoodEntry, PdfFile as _PdfFile, PlanOption as _PlanOption, Trophy as _Trophy, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCourseFolder(arg0: string, arg1: string, arg2: Array<CourseFile>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCourseFolder(arg0, arg1, await to_candid_vec_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCourseFolder(arg0, arg1, await to_candid_vec_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addJournalEntry(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addJournalEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJournalEntry(arg0, arg1);
            return result;
        }
    }
    async addMeetingLink(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMeetingLink(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMeetingLink(arg0, arg1, arg2);
            return result;
        }
    }
    async addMood(arg0: Mood): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMood(to_candid_Mood_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMood(to_candid_Mood_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addOrUpdatePromoCode(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdatePromoCode(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdatePromoCode(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async authenticatePlaybookUser(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.authenticatePlaybookUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authenticatePlaybookUser(arg0, arg1);
            return result;
        }
    }
    async changePlaybookPassword(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.changePlaybookPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changePlaybookPassword(arg0, arg1);
            return result;
        }
    }
    async checkAndHandleCallerExpiration(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAndHandleCallerExpiration();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAndHandleCallerExpiration();
            return result;
        }
    }
    async checkAndHandleSystemExpirations(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAndHandleSystemExpirations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAndHandleSystemExpirations();
            return result;
        }
    }
    async createEvent(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createGoal(arg0: string, arg1: string, arg2: GoalType, arg3: GoalCategory, arg4: bigint, arg5: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createGoal(arg0, arg1, to_candid_GoalType_n16(this._uploadFile, this._downloadFile, arg2), to_candid_GoalCategory_n18(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGoal(arg0, arg1, to_candid_GoalType_n16(this._uploadFile, this._downloadFile, arg2), to_candid_GoalCategory_n18(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async createTrophyTemplate(arg0: string, arg1: string, arg2: string, arg3: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrophyTemplate(arg0, arg1, arg2, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrophyTemplate(arg0, arg1, arg2, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async deleteEvent(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0, arg1);
            return result;
        }
    }
    async deleteJournalEntry(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJournalEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJournalEntry(arg0);
            return result;
        }
    }
    async deleteMeetingLink(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMeetingLink(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMeetingLink(arg0, arg1);
            return result;
        }
    }
    async editEvent(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: bigint, arg5: bigint, arg6: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.editEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCouponCode(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCouponCode();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCouponCode();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourseFolder(arg0: string, arg1: string): Promise<CourseFolder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourseFolder(arg0, arg1);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourseFolder(arg0, arg1);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvents();
            return result;
        }
    }
    async getJournalEntries(): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournalEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournalEntries();
            return result;
        }
    }
    async getMeetingLinks(): Promise<Array<MeetingLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMeetingLinks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMeetingLinks();
            return result;
        }
    }
    async getMoodHistory(): Promise<Array<MoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMoodHistory();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMoodHistory();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonials();
            return result;
        }
    }
    async getUserGoals(arg0: Principal): Promise<Array<Goal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserGoals(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserGoals(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTrophies(arg0: Principal): Promise<Array<Trophy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTrophies(arg0);
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTrophies(arg0);
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async keepTokenActive(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.keepTokenActive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.keepTokenActive(arg0);
            return result;
        }
    }
    async listCourseFolders(): Promise<Array<CourseFolder>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCourseFolders();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCourseFolders();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPdfFiles(): Promise<Array<PdfFile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPdfFiles();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPdfFiles();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProductSuggestions(): Promise<Array<ProductSuggestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProductSuggestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProductSuggestions();
            return result;
        }
    }
    async logoutPlaybookUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logoutPlaybookUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logoutPlaybookUser(arg0);
            return result;
        }
    }
    async recordGroupClassAttendance(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordGroupClassAttendance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordGroupClassAttendance();
            return result;
        }
    }
    async recordPayment(arg0: PlanOption): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPayment(to_candid_PlanOption_n56(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPayment(to_candid_PlanOption_n56(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async recordTherapySession(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordTherapySession();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordTherapySession();
            return result;
        }
    }
    async recordToolUsage(arg0: GoalCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordToolUsage(to_candid_GoalCategory_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordToolUsage(to_candid_GoalCategory_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n58(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n58(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCouponCode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCouponCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCouponCode(arg0);
            return result;
        }
    }
    async savePdfFile(arg0: string, arg1: string, arg2: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePdfFile(arg0, arg1, await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePdfFile(arg0, arg1, await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async selectPlan(arg0: PlanOption): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.selectPlan(to_candid_PlanOption_n56(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selectPlan(to_candid_PlanOption_n56(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitProductSuggestion(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitProductSuggestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitProductSuggestion(arg0);
            return result;
        }
    }
    async submitTestimonial(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTestimonial(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTestimonial(arg0, arg1);
            return result;
        }
    }
    async toggleNewsletterOptIn(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleNewsletterOptIn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleNewsletterOptIn(arg0);
            return result;
        }
    }
    async updateGoalProgress(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGoalProgress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGoalProgress(arg0, arg1);
            return result;
        }
    }
    async updateJournalEntry(arg0: bigint, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJournalEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJournalEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async validatePlaybookToken(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validatePlaybookToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validatePlaybookToken(arg0);
            return result;
        }
    }
}
async function from_candid_CourseFile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CourseFile): Promise<CourseFile> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_CourseFolder_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CourseFolder): Promise<CourseFolder> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_GoalCategory_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalCategory): GoalCategory {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_GoalType_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalType): GoalType {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Goal_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Goal): Goal {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_MoodEntry_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MoodEntry): MoodEntry {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Mood_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Mood): Mood {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
async function from_candid_PdfFile_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PdfFile): Promise<PdfFile> {
    return await from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_PlanOption_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlanOption): PlanOption {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Trophy_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trophy): Trophy {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CourseFolder]): Promise<CourseFolder | null> {
    return value.length === 0 ? null : await from_candid_CourseFolder_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    couponCode: [] | [string];
    planExpirationTimestamp: [] | [bigint];
    planStartTimestamp: [] | [bigint];
    dateOfBirth: [] | [string];
    city: [] | [string];
    newsletterOptIn: boolean;
    name: string;
    isActive: boolean;
    email: [] | [string];
    state: [] | [string];
    phone: [] | [string];
    selectedPlan: _PlanOption;
}): {
    couponCode?: string;
    planExpirationTimestamp?: bigint;
    planStartTimestamp?: bigint;
    dateOfBirth?: string;
    city?: string;
    newsletterOptIn: boolean;
    name: string;
    isActive: boolean;
    email?: string;
    state?: string;
    phone?: string;
    selectedPlan: PlanOption;
} {
    return {
        couponCode: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.couponCode)),
        planExpirationTimestamp: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.planExpirationTimestamp)),
        planStartTimestamp: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.planStartTimestamp)),
        dateOfBirth: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.dateOfBirth)),
        city: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.city)),
        newsletterOptIn: value.newsletterOptIn,
        name: value.name,
        isActive: value.isActive,
        email: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.email)),
        state: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.state)),
        phone: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.phone)),
        selectedPlan: from_candid_PlanOption_n26(_uploadFile, _downloadFile, value.selectedPlan)
    };
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    files: Array<_CourseFile>;
    folderName: string;
}): Promise<{
    files: Array<CourseFile>;
    folderName: string;
}> {
    return {
        files: await from_candid_vec_n33(_uploadFile, _downloadFile, value.files),
        folderName: value.folderName
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: _ExternalBlob;
    fileName: string;
}): Promise<{
    blob: ExternalBlob;
    fileName: string;
}> {
    return {
        blob: await from_candid_ExternalBlob_n36(_uploadFile, _downloadFile, value.blob),
        fileName: value.fileName
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mood: _Mood;
    timestamp: bigint;
}): {
    mood: Mood;
    timestamp: bigint;
} {
    return {
        mood: from_candid_Mood_n40(_uploadFile, _downloadFile, value.mood),
        timestamp: value.timestamp
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    isCompleted: boolean;
    goalType: _GoalType;
    userId: Principal;
    currentProgress: bigint;
    description: string;
    trophyId: [] | [bigint];
    category: _GoalCategory;
    targetValue: bigint;
    completionTimestamp: [] | [bigint];
}): {
    id: bigint;
    title: string;
    isCompleted: boolean;
    goalType: GoalType;
    userId: Principal;
    currentProgress: bigint;
    description: string;
    trophyId?: bigint;
    category: GoalCategory;
    targetValue: bigint;
    completionTimestamp?: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        isCompleted: value.isCompleted,
        goalType: from_candid_GoalType_n45(_uploadFile, _downloadFile, value.goalType),
        userId: value.userId,
        currentProgress: value.currentProgress,
        description: value.description,
        trophyId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.trophyId)),
        category: from_candid_GoalCategory_n47(_uploadFile, _downloadFile, value.category),
        targetValue: value.targetValue,
        completionTimestamp: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.completionTimestamp))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    dateEarned: [] | [bigint];
    discountCode: [] | [string];
    userId: Principal;
    description: string;
    imageIdentifier: string;
    discountPercentage: [] | [bigint];
}): {
    id: bigint;
    title: string;
    dateEarned?: bigint;
    discountCode?: string;
    userId: Principal;
    description: string;
    imageIdentifier: string;
    discountPercentage?: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        dateEarned: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.dateEarned)),
        discountCode: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.discountCode)),
        userId: value.userId,
        description: value.description,
        imageIdentifier: value.imageIdentifier,
        discountPercentage: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.discountPercentage))
    };
}
async function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    blob: _ExternalBlob;
    name: string;
}): Promise<{
    id: bigint;
    blob: ExternalBlob;
    name: string;
}> {
    return {
        id: value.id,
        blob: await from_candid_ExternalBlob_n36(_uploadFile, _downloadFile, value.blob),
        name: value.name
    };
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premierYearly: null;
} | {
    premierMonthly: null;
} | {
    basicSixMonth: null;
} | {
    premierSixMonth: null;
} | {
    free: null;
} | {
    basicYearly: null;
} | {
    basicMonthly: null;
}): PlanOption {
    return "premierYearly" in value ? PlanOption.premierYearly : "premierMonthly" in value ? PlanOption.premierMonthly : "basicSixMonth" in value ? PlanOption.basicSixMonth : "premierSixMonth" in value ? PlanOption.premierSixMonth : "free" in value ? PlanOption.free : "basicYearly" in value ? PlanOption.basicYearly : "basicMonthly" in value ? PlanOption.basicMonthly : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sad: null;
} | {
    happy: null;
} | {
    neutral: null;
}): Mood {
    return "sad" in value ? Mood.sad : "happy" in value ? Mood.happy : "neutral" in value ? Mood.neutral : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    streak: null;
} | {
    milestone: null;
}): GoalType {
    return "streak" in value ? GoalType.streak : "milestone" in value ? GoalType.milestone : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    breathingTool: null;
} | {
    moodLog: null;
} | {
    none: null;
} | {
    therapySession: null;
} | {
    groundingTool: null;
} | {
    groupClass: null;
} | {
    reframingTool: null;
} | {
    journaling: null;
}): GoalCategory {
    return "breathingTool" in value ? GoalCategory.breathingTool : "moodLog" in value ? GoalCategory.moodLog : "none" in value ? GoalCategory.none : "therapySession" in value ? GoalCategory.therapySession : "groundingTool" in value ? GoalCategory.groundingTool : "groupClass" in value ? GoalCategory.groupClass : "reframingTool" in value ? GoalCategory.reframingTool : "journaling" in value ? GoalCategory.journaling : value;
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CourseFile>): Promise<Array<CourseFile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CourseFile_n34(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MoodEntry>): Array<MoodEntry> {
    return value.map((x)=>from_candid_MoodEntry_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Goal>): Array<Goal> {
    return value.map((x)=>from_candid_Goal_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trophy>): Array<Trophy> {
    return value.map((x)=>from_candid_Trophy_n50(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CourseFolder>): Promise<Array<CourseFolder>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CourseFolder_n31(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PdfFile>): Promise<Array<PdfFile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PdfFile_n54(_uploadFile, _downloadFile, x)));
}
async function to_candid_CourseFile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseFile): Promise<_CourseFile> {
    return await to_candid_record_n10(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_GoalCategory_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalCategory): _GoalCategory {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_GoalType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalType): _GoalType {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Mood_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mood): _Mood {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_PlanOption_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanOption): _PlanOption {
    return to_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: ExternalBlob;
    fileName: string;
}): Promise<{
    blob: _ExternalBlob;
    fileName: string;
}> {
    return {
        blob: await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.blob),
        fileName: value.fileName
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    couponCode?: string;
    planExpirationTimestamp?: bigint;
    planStartTimestamp?: bigint;
    dateOfBirth?: string;
    city?: string;
    newsletterOptIn: boolean;
    name: string;
    isActive: boolean;
    email?: string;
    state?: string;
    phone?: string;
    selectedPlan: PlanOption;
}): {
    couponCode: [] | [string];
    planExpirationTimestamp: [] | [bigint];
    planStartTimestamp: [] | [bigint];
    dateOfBirth: [] | [string];
    city: [] | [string];
    newsletterOptIn: boolean;
    name: string;
    isActive: boolean;
    email: [] | [string];
    state: [] | [string];
    phone: [] | [string];
    selectedPlan: _PlanOption;
} {
    return {
        couponCode: value.couponCode ? candid_some(value.couponCode) : candid_none(),
        planExpirationTimestamp: value.planExpirationTimestamp ? candid_some(value.planExpirationTimestamp) : candid_none(),
        planStartTimestamp: value.planStartTimestamp ? candid_some(value.planStartTimestamp) : candid_none(),
        dateOfBirth: value.dateOfBirth ? candid_some(value.dateOfBirth) : candid_none(),
        city: value.city ? candid_some(value.city) : candid_none(),
        newsletterOptIn: value.newsletterOptIn,
        name: value.name,
        isActive: value.isActive,
        email: value.email ? candid_some(value.email) : candid_none(),
        state: value.state ? candid_some(value.state) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none(),
        selectedPlan: to_candid_PlanOption_n56(_uploadFile, _downloadFile, value.selectedPlan)
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mood): {
    sad: null;
} | {
    happy: null;
} | {
    neutral: null;
} {
    return value == Mood.sad ? {
        sad: null
    } : value == Mood.happy ? {
        happy: null
    } : value == Mood.neutral ? {
        neutral: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalType): {
    streak: null;
} | {
    milestone: null;
} {
    return value == GoalType.streak ? {
        streak: null
    } : value == GoalType.milestone ? {
        milestone: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalCategory): {
    breathingTool: null;
} | {
    moodLog: null;
} | {
    none: null;
} | {
    therapySession: null;
} | {
    groundingTool: null;
} | {
    groupClass: null;
} | {
    reframingTool: null;
} | {
    journaling: null;
} {
    return value == GoalCategory.breathingTool ? {
        breathingTool: null
    } : value == GoalCategory.moodLog ? {
        moodLog: null
    } : value == GoalCategory.none ? {
        none: null
    } : value == GoalCategory.therapySession ? {
        therapySession: null
    } : value == GoalCategory.groundingTool ? {
        groundingTool: null
    } : value == GoalCategory.groupClass ? {
        groupClass: null
    } : value == GoalCategory.reframingTool ? {
        reframingTool: null
    } : value == GoalCategory.journaling ? {
        journaling: null
    } : value;
}
function to_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanOption): {
    premierYearly: null;
} | {
    premierMonthly: null;
} | {
    basicSixMonth: null;
} | {
    premierSixMonth: null;
} | {
    free: null;
} | {
    basicYearly: null;
} | {
    basicMonthly: null;
} {
    return value == PlanOption.premierYearly ? {
        premierYearly: null
    } : value == PlanOption.premierMonthly ? {
        premierMonthly: null
    } : value == PlanOption.basicSixMonth ? {
        basicSixMonth: null
    } : value == PlanOption.premierSixMonth ? {
        premierSixMonth: null
    } : value == PlanOption.free ? {
        free: null
    } : value == PlanOption.basicYearly ? {
        basicYearly: null
    } : value == PlanOption.basicMonthly ? {
        basicMonthly: null
    } : value;
}
async function to_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CourseFile>): Promise<Array<_CourseFile>> {
    return await Promise.all(value.map(async (x)=>await to_candid_CourseFile_n9(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
