/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CourseFile = IDL.Record({
  'blob' : ExternalBlob,
  'fileName' : IDL.Text,
});
export const Mood = IDL.Variant({
  'sad' : IDL.Null,
  'happy' : IDL.Null,
  'neutral' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GoalType = IDL.Variant({
  'streak' : IDL.Null,
  'milestone' : IDL.Null,
});
export const GoalCategory = IDL.Variant({
  'breathingTool' : IDL.Null,
  'moodLog' : IDL.Null,
  'none' : IDL.Null,
  'therapySession' : IDL.Null,
  'groundingTool' : IDL.Null,
  'groupClass' : IDL.Null,
  'reframingTool' : IDL.Null,
  'journaling' : IDL.Null,
});
export const PlanOption = IDL.Variant({
  'premierYearly' : IDL.Null,
  'premierMonthly' : IDL.Null,
  'basicSixMonth' : IDL.Null,
  'premierSixMonth' : IDL.Null,
  'free' : IDL.Null,
  'basicYearly' : IDL.Null,
  'basicMonthly' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'couponCode' : IDL.Opt(IDL.Text),
  'planExpirationTimestamp' : IDL.Opt(IDL.Int),
  'planStartTimestamp' : IDL.Opt(IDL.Int),
  'dateOfBirth' : IDL.Opt(IDL.Text),
  'city' : IDL.Opt(IDL.Text),
  'newsletterOptIn' : IDL.Bool,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Opt(IDL.Text),
  'state' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
  'selectedPlan' : PlanOption,
});
export const CourseFolder = IDL.Record({
  'files' : IDL.Vec(CourseFile),
  'folderName' : IDL.Text,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'title' : IDL.Text,
  'endTime' : IDL.Int,
  'description' : IDL.Text,
  'location' : IDL.Text,
});
export const JournalEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const MeetingLink = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const MoodEntry = IDL.Record({ 'mood' : Mood, 'timestamp' : IDL.Int });
export const Testimonial = IDL.Record({
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Goal = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'goalType' : GoalType,
  'userId' : IDL.Principal,
  'currentProgress' : IDL.Nat,
  'description' : IDL.Text,
  'trophyId' : IDL.Opt(IDL.Nat),
  'category' : GoalCategory,
  'targetValue' : IDL.Nat,
  'completionTimestamp' : IDL.Opt(IDL.Int),
});
export const Trophy = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'dateEarned' : IDL.Opt(IDL.Int),
  'discountCode' : IDL.Opt(IDL.Text),
  'userId' : IDL.Principal,
  'description' : IDL.Text,
  'imageIdentifier' : IDL.Text,
  'discountPercentage' : IDL.Opt(IDL.Nat),
});
export const PdfFile = IDL.Record({
  'id' : IDL.Nat,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
});
export const ProductSuggestion = IDL.Record({
  'id' : IDL.Nat,
  'suggestion' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCourseFolder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(CourseFile)],
      [],
      [],
    ),
  'addJournalEntry' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addMeetingLink' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addMood' : IDL.Func([Mood], [], []),
  'addOrUpdatePromoCode' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'authenticatePlaybookUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'changePlaybookPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'checkAndHandleCallerExpiration' : IDL.Func([], [], []),
  'checkAndHandleSystemExpirations' : IDL.Func([], [], []),
  'createEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Text],
      [],
      [],
    ),
  'createGoal' : IDL.Func(
      [IDL.Text, IDL.Text, GoalType, GoalCategory, IDL.Nat, IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'createTrophyTemplate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'deleteEvent' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'deleteJournalEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteMeetingLink' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'editEvent' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCouponCode' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getCourseFolder' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(CourseFolder)],
      ['query'],
    ),
  'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getMeetingLinks' : IDL.Func([], [IDL.Vec(MeetingLink)], ['query']),
  'getMoodHistory' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getUserGoals' : IDL.Func([IDL.Principal], [IDL.Vec(Goal)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTrophies' : IDL.Func([IDL.Principal], [IDL.Vec(Trophy)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'keepTokenActive' : IDL.Func([IDL.Text], [], []),
  'listCourseFolders' : IDL.Func([], [IDL.Vec(CourseFolder)], ['query']),
  'listPdfFiles' : IDL.Func([], [IDL.Vec(PdfFile)], ['query']),
  'listProductSuggestions' : IDL.Func(
      [],
      [IDL.Vec(ProductSuggestion)],
      ['query'],
    ),
  'logoutPlaybookUser' : IDL.Func([IDL.Text], [], []),
  'recordGroupClassAttendance' : IDL.Func([], [], []),
  'recordPayment' : IDL.Func([PlanOption], [], []),
  'recordTherapySession' : IDL.Func([], [], []),
  'recordToolUsage' : IDL.Func([GoalCategory], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCouponCode' : IDL.Func([IDL.Text], [], []),
  'savePdfFile' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
  'selectPlan' : IDL.Func([PlanOption], [], []),
  'submitProductSuggestion' : IDL.Func([IDL.Text], [], []),
  'submitTestimonial' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'toggleNewsletterOptIn' : IDL.Func([IDL.Bool], [], []),
  'updateGoalProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateJournalEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'validatePlaybookToken' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CourseFile = IDL.Record({
    'blob' : ExternalBlob,
    'fileName' : IDL.Text,
  });
  const Mood = IDL.Variant({
    'sad' : IDL.Null,
    'happy' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GoalType = IDL.Variant({ 'streak' : IDL.Null, 'milestone' : IDL.Null });
  const GoalCategory = IDL.Variant({
    'breathingTool' : IDL.Null,
    'moodLog' : IDL.Null,
    'none' : IDL.Null,
    'therapySession' : IDL.Null,
    'groundingTool' : IDL.Null,
    'groupClass' : IDL.Null,
    'reframingTool' : IDL.Null,
    'journaling' : IDL.Null,
  });
  const PlanOption = IDL.Variant({
    'premierYearly' : IDL.Null,
    'premierMonthly' : IDL.Null,
    'basicSixMonth' : IDL.Null,
    'premierSixMonth' : IDL.Null,
    'free' : IDL.Null,
    'basicYearly' : IDL.Null,
    'basicMonthly' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'couponCode' : IDL.Opt(IDL.Text),
    'planExpirationTimestamp' : IDL.Opt(IDL.Int),
    'planStartTimestamp' : IDL.Opt(IDL.Int),
    'dateOfBirth' : IDL.Opt(IDL.Text),
    'city' : IDL.Opt(IDL.Text),
    'newsletterOptIn' : IDL.Bool,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Opt(IDL.Text),
    'state' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
    'selectedPlan' : PlanOption,
  });
  const CourseFolder = IDL.Record({
    'files' : IDL.Vec(CourseFile),
    'folderName' : IDL.Text,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'title' : IDL.Text,
    'endTime' : IDL.Int,
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  const JournalEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const MeetingLink = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const MoodEntry = IDL.Record({ 'mood' : Mood, 'timestamp' : IDL.Int });
  const Testimonial = IDL.Record({
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Goal = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'goalType' : GoalType,
    'userId' : IDL.Principal,
    'currentProgress' : IDL.Nat,
    'description' : IDL.Text,
    'trophyId' : IDL.Opt(IDL.Nat),
    'category' : GoalCategory,
    'targetValue' : IDL.Nat,
    'completionTimestamp' : IDL.Opt(IDL.Int),
  });
  const Trophy = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'dateEarned' : IDL.Opt(IDL.Int),
    'discountCode' : IDL.Opt(IDL.Text),
    'userId' : IDL.Principal,
    'description' : IDL.Text,
    'imageIdentifier' : IDL.Text,
    'discountPercentage' : IDL.Opt(IDL.Nat),
  });
  const PdfFile = IDL.Record({
    'id' : IDL.Nat,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
  });
  const ProductSuggestion = IDL.Record({
    'id' : IDL.Nat,
    'suggestion' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCourseFolder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(CourseFile)],
        [],
        [],
      ),
    'addJournalEntry' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addMeetingLink' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addMood' : IDL.Func([Mood], [], []),
    'addOrUpdatePromoCode' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'authenticatePlaybookUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'changePlaybookPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'checkAndHandleCallerExpiration' : IDL.Func([], [], []),
    'checkAndHandleSystemExpirations' : IDL.Func([], [], []),
    'createEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Text],
        [],
        [],
      ),
    'createGoal' : IDL.Func(
        [IDL.Text, IDL.Text, GoalType, GoalCategory, IDL.Nat, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'createTrophyTemplate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'deleteEvent' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'deleteJournalEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteMeetingLink' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'editEvent' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCouponCode' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getCourseFolder' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(CourseFolder)],
        ['query'],
      ),
    'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'getMeetingLinks' : IDL.Func([], [IDL.Vec(MeetingLink)], ['query']),
    'getMoodHistory' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getUserGoals' : IDL.Func([IDL.Principal], [IDL.Vec(Goal)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTrophies' : IDL.Func([IDL.Principal], [IDL.Vec(Trophy)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'keepTokenActive' : IDL.Func([IDL.Text], [], []),
    'listCourseFolders' : IDL.Func([], [IDL.Vec(CourseFolder)], ['query']),
    'listPdfFiles' : IDL.Func([], [IDL.Vec(PdfFile)], ['query']),
    'listProductSuggestions' : IDL.Func(
        [],
        [IDL.Vec(ProductSuggestion)],
        ['query'],
      ),
    'logoutPlaybookUser' : IDL.Func([IDL.Text], [], []),
    'recordGroupClassAttendance' : IDL.Func([], [], []),
    'recordPayment' : IDL.Func([PlanOption], [], []),
    'recordTherapySession' : IDL.Func([], [], []),
    'recordToolUsage' : IDL.Func([GoalCategory], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCouponCode' : IDL.Func([IDL.Text], [], []),
    'savePdfFile' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
    'selectPlan' : IDL.Func([PlanOption], [], []),
    'submitProductSuggestion' : IDL.Func([IDL.Text], [], []),
    'submitTestimonial' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'toggleNewsletterOptIn' : IDL.Func([IDL.Bool], [], []),
    'updateGoalProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateJournalEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'validatePlaybookToken' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };