/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CourseFile { 'blob' : ExternalBlob, 'fileName' : string }
export interface CourseFolder {
  'files' : Array<CourseFile>,
  'folderName' : string,
}
export interface Event {
  'id' : bigint,
  'startTime' : bigint,
  'title' : string,
  'endTime' : bigint,
  'description' : string,
  'location' : string,
}
export type ExternalBlob = Uint8Array;
export interface Goal {
  'id' : bigint,
  'title' : string,
  'isCompleted' : boolean,
  'goalType' : GoalType,
  'userId' : Principal,
  'currentProgress' : bigint,
  'description' : string,
  'trophyId' : [] | [bigint],
  'category' : GoalCategory,
  'targetValue' : bigint,
  'completionTimestamp' : [] | [bigint],
}
export type GoalCategory = { 'breathingTool' : null } |
  { 'moodLog' : null } |
  { 'none' : null } |
  { 'therapySession' : null } |
  { 'groundingTool' : null } |
  { 'groupClass' : null } |
  { 'reframingTool' : null } |
  { 'journaling' : null };
export type GoalType = { 'streak' : null } |
  { 'milestone' : null };
export interface JournalEntry {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'timestamp' : bigint,
}
export interface MeetingLink {
  'id' : bigint,
  'url' : string,
  'title' : string,
  'timestamp' : bigint,
}
export type Mood = { 'sad' : null } |
  { 'happy' : null } |
  { 'neutral' : null };
export interface MoodEntry { 'mood' : Mood, 'timestamp' : bigint }
export interface PdfFile {
  'id' : bigint,
  'blob' : ExternalBlob,
  'name' : string,
}
export type PlanOption = { 'premierYearly' : null } |
  { 'premierMonthly' : null } |
  { 'basicSixMonth' : null } |
  { 'premierSixMonth' : null } |
  { 'free' : null } |
  { 'basicYearly' : null } |
  { 'basicMonthly' : null };
export interface ProductSuggestion {
  'id' : bigint,
  'suggestion' : string,
  'author' : Principal,
  'timestamp' : bigint,
}
export interface Testimonial {
  'name' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface Trophy {
  'id' : bigint,
  'title' : string,
  'dateEarned' : [] | [bigint],
  'discountCode' : [] | [string],
  'userId' : Principal,
  'description' : string,
  'imageIdentifier' : string,
  'discountPercentage' : [] | [bigint],
}
export interface UserProfile {
  'couponCode' : [] | [string],
  'planExpirationTimestamp' : [] | [bigint],
  'planStartTimestamp' : [] | [bigint],
  'dateOfBirth' : [] | [string],
  'city' : [] | [string],
  'newsletterOptIn' : boolean,
  'name' : string,
  'isActive' : boolean,
  'email' : [] | [string],
  'state' : [] | [string],
  'phone' : [] | [string],
  'selectedPlan' : PlanOption,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCourseFolder' : ActorMethod<
    [string, string, Array<CourseFile>],
    undefined
  >,
  'addJournalEntry' : ActorMethod<[string, string], bigint>,
  'addMeetingLink' : ActorMethod<[string, string, string], undefined>,
  'addMood' : ActorMethod<[Mood], undefined>,
  'addOrUpdatePromoCode' : ActorMethod<[string, string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'authenticatePlaybookUser' : ActorMethod<[string, string], boolean>,
  'changePlaybookPassword' : ActorMethod<[string, string], undefined>,
  'checkAndHandleCallerExpiration' : ActorMethod<[], undefined>,
  'checkAndHandleSystemExpirations' : ActorMethod<[], undefined>,
  'createEvent' : ActorMethod<
    [string, string, string, bigint, bigint, string],
    undefined
  >,
  'createGoal' : ActorMethod<
    [string, string, GoalType, GoalCategory, bigint, [] | [bigint]],
    bigint
  >,
  'createTrophyTemplate' : ActorMethod<
    [string, string, string, [] | [bigint]],
    bigint
  >,
  'deleteEvent' : ActorMethod<[string, bigint], boolean>,
  'deleteJournalEntry' : ActorMethod<[bigint], boolean>,
  'deleteMeetingLink' : ActorMethod<[string, bigint], boolean>,
  'editEvent' : ActorMethod<
    [string, bigint, string, string, bigint, bigint, string],
    boolean
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCouponCode' : ActorMethod<[], [] | [string]>,
  'getCourseFolder' : ActorMethod<[string, string], [] | [CourseFolder]>,
  'getEvents' : ActorMethod<[], Array<Event>>,
  'getJournalEntries' : ActorMethod<[], Array<JournalEntry>>,
  'getMeetingLinks' : ActorMethod<[], Array<MeetingLink>>,
  'getMoodHistory' : ActorMethod<[], Array<MoodEntry>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getUserGoals' : ActorMethod<[Principal], Array<Goal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTrophies' : ActorMethod<[Principal], Array<Trophy>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'keepTokenActive' : ActorMethod<[string], undefined>,
  'listCourseFolders' : ActorMethod<[], Array<CourseFolder>>,
  'listPdfFiles' : ActorMethod<[], Array<PdfFile>>,
  'listProductSuggestions' : ActorMethod<[], Array<ProductSuggestion>>,
  'logoutPlaybookUser' : ActorMethod<[string], undefined>,
  'recordGroupClassAttendance' : ActorMethod<[], undefined>,
  'recordPayment' : ActorMethod<[PlanOption], undefined>,
  'recordTherapySession' : ActorMethod<[], undefined>,
  'recordToolUsage' : ActorMethod<[GoalCategory], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCouponCode' : ActorMethod<[string], undefined>,
  'savePdfFile' : ActorMethod<[string, string, ExternalBlob], undefined>,
  'selectPlan' : ActorMethod<[PlanOption], undefined>,
  'submitProductSuggestion' : ActorMethod<[string], undefined>,
  'submitTestimonial' : ActorMethod<[string, string], undefined>,
  'toggleNewsletterOptIn' : ActorMethod<[boolean], undefined>,
  'updateGoalProgress' : ActorMethod<[bigint, bigint], undefined>,
  'updateJournalEntry' : ActorMethod<[bigint, string, string], boolean>,
  'validatePlaybookToken' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];